site_name: DevOps Documentation Hub
site_url: https://aya-hamed1.github.io/
docs_dir: .
site_dir: docs

plugins:
  - same-dir
  - search
  - git-revision-date
  - mermaid2

repo_url: https://github.com/aya-hamed1/aya-hamed1.github.io
repo_name: DevOps-Docs
edit_uri: edit/master/

theme: 
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: default
    primary: red
    accent: pink
  logo: assets/vois_logo.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.follow

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-MSG4VS6C36
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve by
            <a href="mailto:aya.eid@vodafone.com" target="_blank" rel="noopener">sending us</a> a mail .
extra_css:
    - assets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 

nav:
    - Getting started: README.md
